name: Mi Robot Garmin
on:
  schedule:
    - cron: '0 07 * * *' # Esto hará que corra todos los días a las 7:00 AM
  workflow_dispatch: # Esto nos permite activarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar mi copia
        uses: actions/checkout@v3

      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar herramientas de Garmin
        run: pip install garminconnect

      - name: Ejecutar Extracción de Datos
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: |
          python -c "
          import os
          from garminconnect import Garmin
          client = Garmin(os.getenv('GARMIN_EMAIL'), os.getenv('GARMIN_PASSWORD'))
          client.login()
          stats = client.get_stats('2026-04-06') # Esto se ajustará solo luego
          with open('mis_datos_garmin.txt', 'w') as f:
              f.write(str(stats))
          "
      - name: Guardar datos en mi GitHub
        run: |
          git config --global user.name 'GarminRobot'
          git config --global user.email 'robot@github.com'
          git add mis_datos_garmin.txt
          git commit -m 'Actualización diaria de mis datos' || exit 0
          git push
