name: Mi Robot Garmin
on:
  schedule:
    - cron: '0 07 * * *'
  workflow_dispatch:

permissions: # Esto le da permiso extra al robot para escribir
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar mi copia
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar herramientas de Garmin
        run: pip install garminconnect

      - name: Ejecutar Extracción de Datos
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: |
          python -c "
          import os
          from garminconnect import Garmin
          from datetime import date
          try:
              client = Garmin(os.getenv('GARMIN_EMAIL'), os.getenv('GARMIN_PASSWORD'))
              client.login()
              # Usamos la fecha de hoy automáticamente
              stats = client.get_stats(date.today().isoformat())
              with open('mis_datos_garmin.txt', 'w') as f:
                  f.write(str(stats))
              print('Datos extraídos con éxito')
          except Exception as e:
              print(f'Error: {e}')
              exit(1)
          "
      - name: Guardar datos en mi GitHub
        run: |
          git config --global user.name 'GarminRobot'
          git config --global user.email 'robot@github.com'
          git add mis_datos_garmin.txt
          git commit -m 'Actualización diaria' || echo "Sin cambios para subir"
          git push
